# Generated by Django 3.1.1 on 2020-12-20 23:21

import TimeManagerBackend.apps.images.models.fields
import TimeManagerBackend.apps.images.models.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfilePicture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_hash', models.TextField(null=True)),
                ('image', TimeManagerBackend.apps.images.models.fields.GooglePublicImageField(null=True, upload_to=TimeManagerBackend.apps.images.models.models.get_user_filename)),
                ('background', models.IntegerField()),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
