version: "3.4"

services:
  firebase:
    environment:
      - ENV_TEST=1

  cloud-storage:
    volumes:
      - ./test-gcs-data:/data

  database:
    volumes:
      - ./test-postgres-data:/var/lib/postgresql/data:rw
